//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioWeb.ClienteConsola.ServiceFicherosGarumWCF {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ficherosgarum", Namespace="http://schemas.datacontract.org/2004/07/ServiciosWeb.Datos")]
    [System.SerializableAttribute()]
    public partial class ficherosgarum : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> Fecha_EstudioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> Fecha_FicheroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDFicheroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nombre_EstacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nombre_FicheroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TPVField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Fecha_Estudio {
            get {
                return this.Fecha_EstudioField;
            }
            set {
                if ((this.Fecha_EstudioField.Equals(value) != true)) {
                    this.Fecha_EstudioField = value;
                    this.RaisePropertyChanged("Fecha_Estudio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Fecha_Fichero {
            get {
                return this.Fecha_FicheroField;
            }
            set {
                if ((this.Fecha_FicheroField.Equals(value) != true)) {
                    this.Fecha_FicheroField = value;
                    this.RaisePropertyChanged("Fecha_Fichero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDFichero {
            get {
                return this.IDFicheroField;
            }
            set {
                if ((this.IDFicheroField.Equals(value) != true)) {
                    this.IDFicheroField = value;
                    this.RaisePropertyChanged("IDFichero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre_Estacion {
            get {
                return this.Nombre_EstacionField;
            }
            set {
                if ((object.ReferenceEquals(this.Nombre_EstacionField, value) != true)) {
                    this.Nombre_EstacionField = value;
                    this.RaisePropertyChanged("Nombre_Estacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre_Fichero {
            get {
                return this.Nombre_FicheroField;
            }
            set {
                if ((object.ReferenceEquals(this.Nombre_FicheroField, value) != true)) {
                    this.Nombre_FicheroField = value;
                    this.RaisePropertyChanged("Nombre_Fichero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TPV {
            get {
                return this.TPVField;
            }
            set {
                if ((object.ReferenceEquals(this.TPVField, value) != true)) {
                    this.TPVField = value;
                    this.RaisePropertyChanged("TPV");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceFicherosGarumWCF.IServicioFicherosGarum")]
    public interface IServicioFicherosGarum {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFicherosGarum/ObtenerFicheros", ReplyAction="http://tempuri.org/IServicioFicherosGarum/ObtenerFicherosResponse")]
        ServicioWeb.ClienteConsola.ServiceFicherosGarumWCF.ficherosgarum[] ObtenerFicheros();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFicherosGarum/ObtenerFicheros", ReplyAction="http://tempuri.org/IServicioFicherosGarum/ObtenerFicherosResponse")]
        System.Threading.Tasks.Task<ServicioWeb.ClienteConsola.ServiceFicherosGarumWCF.ficherosgarum[]> ObtenerFicherosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioFicherosGarumChannel : ServicioWeb.ClienteConsola.ServiceFicherosGarumWCF.IServicioFicherosGarum, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioFicherosGarumClient : System.ServiceModel.ClientBase<ServicioWeb.ClienteConsola.ServiceFicherosGarumWCF.IServicioFicherosGarum>, ServicioWeb.ClienteConsola.ServiceFicherosGarumWCF.IServicioFicherosGarum {
        
        public ServicioFicherosGarumClient() {
        }
        
        public ServicioFicherosGarumClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioFicherosGarumClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioFicherosGarumClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioFicherosGarumClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ServicioWeb.ClienteConsola.ServiceFicherosGarumWCF.ficherosgarum[] ObtenerFicheros() {
            return base.Channel.ObtenerFicheros();
        }
        
        public System.Threading.Tasks.Task<ServicioWeb.ClienteConsola.ServiceFicherosGarumWCF.ficherosgarum[]> ObtenerFicherosAsync() {
            return base.Channel.ObtenerFicherosAsync();
        }
    }
}
