//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioWeb.Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IncidenciasGarumConnectionEntities : DbContext
    {
        public IncidenciasGarumConnectionEntities()
            : base("name=IncidenciasGarumConnectionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EstudioAjustes> EstudioAjustes { get; set; }
        public virtual DbSet<ficherosgarum> ficherosgarum { get; set; }
    }
}
