//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosWeb.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ficherosgarum
    {
        public int IDFichero { get; set; }
        public Nullable<System.DateTime> Fecha_Estudio { get; set; }
        public Nullable<System.DateTime> Fecha_Fichero { get; set; }
        public string Nombre_Estacion { get; set; }
        public string Nombre_Fichero { get; set; }
        public string TPV { get; set; }
    }
}
